### ISSUE TITLE
Broken relocation code

### ISSUE THREAD

**Issue by CTCaer** [rajkosto/memloader#4]
The current relocation code is broken.

That makes the current implementations of memloader, biskeydump, etc, hang if the loading address is not 0x40010000 and thus skipping that part.

Do you want me to create a PR for this when I have time?
(Currently, I attach a reloc code for payloads in hekate's payload launching, but I don't like it because it's a solution that limits the payload size like what fusee does.)

**Comment by rajkosto** [comment]
why would the loading address ever be anything other than 0x40010000 though ?

**Comment by CTCaer** [comment]
With the same mindset, why they even have a relocator?

There are many reasons why load from another address.
And why a payload should also have a relocator code.

- Optimizing injectors to fit bigger payloads?
- Payload launching from DRAM?
- Other "sercret" exploits? (*ahem.. warmboot..)
- Future-proofing (autonomous compatibility)?

Take a pick.
If the payload does not have a relocator in these cases, then it's incompatible.
Even memloader could launch iram-bpmp payloads.

On-topic now, the broken reloc code:
So the plan is to remove, fix or leave it as is?

**Comment by rajkosto** [comment]
it should get fixed, but if you have a chainloader you would need to detect the need of the payload to run from 40010000 and prepend/replace it with your own in that case (because not everything will get recompiled)

**Comment by rajkosto** [comment]
If you have working relocation .s code for this type of payload (it is fusee, not hekate based), can you submit it as a pull request ?

**Comment by CTCaer** [comment]
I don't. And I don't know if I'll have time to make one.
All that I'm using in hekate (internally) is hekate's relocation code, albeit patched for the needs of each payload.

If you want it for your project, better wait. New hekate will features that you'll like.

(offtopic, I can PR another important change for memloader though).

**Comment by rajkosto** [comment]
What's that ? The memloader PR ? Fix the PLL inits so that nouveau works in linux when booted through it ?

**Comment by CTCaer** [comment]
Hmm no. It's just a pmic change. It changes the force power off from 12s to 4s.

For nouveau to work it needs many other changes

Edit:
Huh? Where's my PR? Github playing games

**Comment by rajkosto** [comment]
nouveau shouldnt need that many changes, i guessed PLL because thats the only thing in memloader that remains from hwinit, all the memory, carveouts, etc stuff i took from coreboot while i was trying to get linux to boot.

I have the code for the PMIC change already, someone suggested it in discord for faster payload debugging ;). Guess it is important if you only use memloader for u-boot ums modes (can fork u-boot and have it halt on gpio button press too, which i probably should, because right now the u-boot that comes with the sample is actually parsing partition tables and trying to mount FAT32 filesystems before it goes into ums, for some reason).

**Comment by CTCaer** [comment]
It's trying to boot, that's why it tries to mount things before ums. You need to change that behavior. Also dunno about custom Chainloading to uboot, but you can use coreboot for that when my new version is going to be released

**Comment by rajkosto** [comment]
It's not trying to boot (if you connect uart you can see its just press key to halt script 3, 2, 1...), but as part of its normal initialization routine before anything it tries to find all partitions and filesystems it can (because even for ums mode you can give it a specific partition too, not just physical but logical)

And by "booting linux" of course i mean through coreboot, just skipping romstage, going directly to ramstage, which when done with memloader gets the kernel running, but nouveau has constant FIFO timeouts.

**Comment by CTCaer** [comment]
Well there will be no need for skipping bootblock and romstage in the feature.
Imo current coreboot needs fixes to a lot hardware configs. Also you can't boot Linux as is without changes to memloader. Otherwise there gonna be cases where it halts at bl31 or to another stage. Can't remember.

**Comment by rajkosto** [comment]
nah, it boots as consistently as with shofEL, and you can see the kernel initial console just get spammed with FIFO timeouts (if that line is compiled out of the driver, it doesnt get to gui anyway)

try it
`cbfs2ini --add-section=FMAP --add-archive=* --skip-archive=fallback/romstage --load-addr=0xcff00000 --boot=fallback/ramstage path/to/coreboot.rom --out=corebootmeup.ini`

(the reason to skip bootblock and romstage is because they only know how to load themselves and the CBFS sections via USB, while with memloader i want to supply them myself)

(you can do that but change --boot to --boot=payload/u-boot if you want to run u-boot with faster memory speeds too)

**Comment by CTCaer** [comment]
Well you can't boot linux without these 2 though and have no problems occur.
They do some important hw init. 
Which is not compatible with nintendo's config.
Also the GPU gpio is enabled there. Check pmic_init

**Comment by rajkosto** [comment]
Does https://github.com/rajkosto/memloader/commit/3ede17e6e8fe485309a893a61f8acfb8bada144f fix relocator ?
I've tested it in emulator and it correctly copies over the entire payload if you launch it from 80000000 but I'm sure you had a specific reason for asking for it to be fixed, so can you test there ?

**Comment by CTCaer** [comment]
I played around. It seems fixed.
